### ISSUE TITLE
cxf配置问题

### ISSUE THREAD

**Issue by Etianliang** [majinding/webservice#27]
项目环境：maven+ssm
jar：<dependency>
		    <groupId>org.apache.cxf.karaf</groupId>
		    <artifactId>apache-cxf</artifactId>
		    <version>3.2.0</version>
		    <type>pom</type>
		    <scope>test</scope>
		</dependency>

错误:
java.lang.ClassNotFoundException: org.apache.cxf.transport.servlet.CXFServlet
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:532)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:142)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1088)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5176)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5460)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

配置文件
我是根据这个博客学习的：https://blog.csdn.net/sms15732621690/article/details/79603661

**Comment by majinding** [comment]
![image](https://user-images.githubusercontent.com/2681645/88925077-a271ea00-d2a6-11ea-9f90-7bd1af0a56dd.png)
 
看了下评论, 1年前就有人提出此问题, 在网上找资料到时候最好先看下评论, 如果成功,最好自己也给个评论,方便你我他

**Comment by majinding** [comment]
spring + cxf的demo 可以参考 https://github.com/majinding/webservice-demo/tree/master/ws-cxf-server-spring
